name: Build and deploy container app to Azure Function App

on:
  push:
    branches:
      - feature/deploy-with-exist-stroge-with-terrafrom

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: services

    environment:
      name: 'production'
      url: ${{ steps.deploy-to-functions.outputs.app-url }}

    strategy:
      matrix:
        directory:
          # - emails/**'
          # - subscriptions/**'
          - emails/func-emails
          - subscriptions/func-subscriptions-automation
          - subscriptions/func-subscriptions-list

    steps:
    - name: ðŸ“‚ Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: ðŸ”Ž Determine modified directory
      id: determine_directory
      run: |
        git diff --name-only HEAD~1 ${{ github.sha }} > changes.txt
        if grep -q '^${{ matrix.directory }}' changes.txt; then
          echo "${{ matrix.directory }} has changes"
          # echo "::set-output name=directory::${{ matrix.directory }}"
          echo "DIRECTORY=${{ matrix.directory }}" >> "$GITHUB_ENV"
        else
          echo "No changes in ${{ matrix.directory }}"
          exit 0
        fi


    - run: |
        echo "DIRECTORY=${{ matrix.directory }}" >> "$GITHUB_ENV"

    - run: |
        echo "WORKING_DIRECTORY=trraform-for-run" >> "$GITHUB_ENV"

    - name: ðŸ› ï¸ Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      if: env.DIRECTORY == matrix.directory
      

    - name: ðŸ”‘ Log in to registry
      uses: docker/login-action@v2
      with:
        registry:  ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      if: env.DIRECTORY == matrix.directory

    - name: ðŸ”– Get release tag name
      id: get_release
      uses: cardinalby/git-get-release-action@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        latest: true
      if: env.DIRECTORY == matrix.directory

    

    - name: ðŸ”„ downcase REPO
      uses: ASzc/change-string-case-action@v1
      id: downcase
      with:
          string: ${{ github.repository }}
      if: env.DIRECTORY == matrix.directory

    - name: â™»ï¸ Set correct environment
      run: |
        TAG=${{ steps.get_release.outputs.tag_name }}
        echo "TAG=$TAG" >> "$GITHUB_ENV"
        REPO=${{ steps.downcase.outputs.lowercase }}
        echo "REPO=$REPO" >> "$GITHUB_ENV"
      if: env.DIRECTORY == matrix.directory

    - name: ðŸ³ Docker metadata
      id: docker_meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ env.REPO }}-${{ matrix.directory }}
        tags: |
          type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ env.TAG }}
          type=semver,pattern={{major}}.{{minor}},value=${{ env.TAG }}
          type=semver,pattern={{major}},value=${{ env.TAG }}
      if: env.DIRECTORY == matrix.directory
    
    - name: ðŸ§° Check and copy necessary files
      run: |
        DIRECTORY=${{ matrix.directory }}
        REQUIRED_FILES=(".funcignore" ".gitignore" "host.json" "local.settings.json" "requirements.txt" "Dockerfile")
        ROOT_DIRECTORY=$(pwd)
        FILES_PATH="$ROOT_DIRECTORY"
        for file in "${REQUIRED_FILES[@]}"; do
          if [ ! -f "${FILES_PATH}/${file}" ]; then
            echo "${file} not found in ${FILES_PATH}, cannot copy"
          else
            echo "${file} found in ${FILES_PATH}, copying from there"
            cp "${FILES_PATH}/${file}" "${ROOT_DIRECTORY}/${DIRECTORY}/"
          fi
        done

    - name: ðŸ—ï¸ Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: ./services/${{ matrix.directory }}
        push: true
        tags: ghcr.io/${{ env.REPO }}-${{ matrix.directory }}:${{ steps.get_release.outputs.tag_name }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        file: ./services/Dockerfile
      if: env.DIRECTORY == matrix.directory

    - name: ðŸ”‘ Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      if: env.DIRECTORY == matrix.directory

    - name: ðŸ”„ Extract last directory level
      run: |
        LAST_LEVEL=$(basename ${{ matrix.directory }})
        echo "LAST_LEVEL=${LAST_LEVEL}" >> "$GITHUB_ENV"
      id: get-last-level
    
    - name: ðŸš€ Deploy to Azure Functions
      id: deploy-to-functions
      uses: Azure/functions-container-action@v1
      with:
        app-name: ${{ env.LAST_LEVEL }}
        image: 'ghcr.io/${{ env.REPO }}-${{ env.LAST_LEVEL }}:${{ steps.get_release.outputs.tag_name }}'   